# Generated by Django 4.2 on 2023-04-25 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='experience',
            new_name='experience_years',
        ),
    ]
